//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DilProjesi.Resources.Views.Anasayfa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_tr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DilProjesi.Resources.Views.Anasayfa.Index-tr", typeof(Index_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgelerimiz.
        /// </summary>
        internal static string belgelerimiz {
            get {
                return ResourceManager.GetString("belgelerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirimler.
        /// </summary>
        internal static string bildirimler {
            get {
                return ResourceManager.GetString("bildirimler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi Güvenliği .
        /// </summary>
        internal static string bilgiguvenligi {
            get {
                return ResourceManager.GetString("bilgiguvenligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkar Çatışması.
        /// </summary>
        internal static string cikarcatismasi {
            get {
                return ResourceManager.GetString("cikarcatismasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çözüm Ortaklarımız.
        /// </summary>
        internal static string cozumortaklarimiz {
            get {
                return ResourceManager.GetString("cozumortaklarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değerlendirme.
        /// </summary>
        internal static string degerlendirme {
            get {
                return ResourceManager.GetString("degerlendirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destek Merkezi .
        /// </summary>
        internal static string destekmerkezi {
            get {
                return ResourceManager.GetString("destekmerkezi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Risk Bildirimi .
        /// </summary>
        internal static string genelriskbildirimi {
            get {
                return ResourceManager.GetString("genelriskbildirimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerekli Fona Nasıl ulaşırım .
        /// </summary>
        internal static string gereklifonanasilulasirim {
            get {
                return ResourceManager.GetString("gereklifonanasilulasirim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girişimci.
        /// </summary>
        internal static string girisimci {
            get {
                return ResourceManager.GetString("girisimci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girişim Sermayesi Yatırım Fonları .
        /// </summary>
        internal static string girisimsermayasiyatirimfonlari {
            get {
                return ResourceManager.GetString("girisimsermayasiyatirimfonlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSYF.
        /// </summary>
        internal static string gsyf {
            get {
                return ResourceManager.GetString("gsyf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda .
        /// </summary>
        internal static string hakkimizda {
            get {
                return ResourceManager.GetString("hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hissedarlar.
        /// </summary>
        internal static string hissedarlar {
            get {
                return ResourceManager.GetString("hissedarlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        internal static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalite.
        /// </summary>
        internal static string kalite {
            get {
                return ResourceManager.GetString("kalite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamuoyu Aydınlatma .
        /// </summary>
        internal static string kamoyuaydinlatma {
            get {
                return ResourceManager.GetString("kamoyuaydinlatma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanyalar.
        /// </summary>
        internal static string kampanyalar {
            get {
                return ResourceManager.GetString("kampanyalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanya Sözleşmesi.
        /// </summary>
        internal static string kampanyasozlesmesi {
            get {
                return ResourceManager.GetString("kampanyasozlesmesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kara Para İle Mücadale.
        /// </summary>
        internal static string karaparailemucadele {
            get {
                return ResourceManager.GetString("karaparailemucadele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurumsal.
        /// </summary>
        internal static string kurumsal {
            get {
                return ResourceManager.GetString("kurumsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVKK Bildirimi .
        /// </summary>
        internal static string kvkkbildirimi {
            get {
                return ResourceManager.GetString("kvkkbildirimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melek Yatırım Ağı.
        /// </summary>
        internal static string melekyatirimagi {
            get {
                return ResourceManager.GetString("melekyatirimagi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politikalar.
        /// </summary>
        internal static string politikalar {
            get {
                return ResourceManager.GetString("politikalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeni Gönder.
        /// </summary>
        internal static string projenigonder {
            get {
                return ResourceManager.GetString("projenigonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rüşvet Ve Yolsuzluk Mücadalesi .
        /// </summary>
        internal static string rusvetveyolsuzluklamucadele {
            get {
                return ResourceManager.GetString("rusvetveyolsuzluklamucadele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sermaye Piyasası Kurulu .
        /// </summary>
        internal static string sermayepiyasasikurulu {
            get {
                return ResourceManager.GetString("sermayepiyasasikurulu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takımımız.
        /// </summary>
        internal static string takimimiz {
            get {
                return ResourceManager.GetString("takimimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Kampanylar.
        /// </summary>
        internal static string tumkampanyalar {
            get {
                return ResourceManager.GetString("tumkampanyalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyelik Sözleşmesi.
        /// </summary>
        internal static string uyeliksozlesmesi {
            get {
                return ResourceManager.GetString("uyeliksozlesmesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatırımcı.
        /// </summary>
        internal static string yatirimci {
            get {
                return ResourceManager.GetString("yatirimci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatırımı Komitesi .
        /// </summary>
        internal static string yatirimkomitesi {
            get {
                return ResourceManager.GetString("yatirimkomitesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatırım Yap.
        /// </summary>
        internal static string yatirimyap {
            get {
                return ResourceManager.GetString("yatirimyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim Kurulu.
        /// </summary>
        internal static string yonetimkurulu {
            get {
                return ResourceManager.GetString("yonetimkurulu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim Kurulumuz.
        /// </summary>
        internal static string yonetimkurulumuz {
            get {
                return ResourceManager.GetString("yonetimkurulumuz", resourceCulture);
            }
        }
    }
}
